# Generated by Django 4.0.3 on 2022-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=512)),
                ('movieAdvisory', models.CharField(max_length=512)),
                ('movieImgUrl', models.CharField(max_length=512)),
                ('movieDuration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
